name: Render Family Tree Image

on:
  push:
    paths:
      - 'docs/data.json'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Serve Site & Render
        run: |
          npx serve . -l 8080 &
          sleep 5
          npm run render

      - name: Commit PNG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/image.png
          git commit -m "Auto-update tree image"
          git push
